repos:
- repo: local
  hooks:
  - id: commit-msg-check
    name: Commit message check
    entry: pre-commit/commit-msg-check.sh
    language: script
    stages: [commit-msg]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format


